- name: Wait for the initial password to be generated
  wait_for:
    path: /data/jenkins/secrets/initialAdminPassword

- name: Password is retrieved
  shell: docker exec -t jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: password_result

- debug:
    msg: "Please open http://{{ facter_ipaddress_eth1 }}:8080 and configure Jenkins. The initial password is: {{ password_result.stdout }}"

- name: Wait for the setup to finish
  wait_for:
    path: /data/jenkins/jenkins.install.InstallUtil.lastExecVersion