- name: Docker repository is added and cache is updated
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} {{ release }}"
    update_cache: yes
    state: present

- name: Debian Docker is present
  apt:
    name: docker-engine
    force: yes

- name: Debian files are present
  template:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_result

- name: User is added to the docker group
  user:
    name: ubuntu
    group: docker
  register: user_result

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
