version: '2'

services:

  registry:
    container_name: jenkins
    image: jenkins:2.3-alpine
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    restart: always
